### ISSUE TITLE
Annotation File Error : Pattern is Required

### ISSUE THREAD

**Issue by mariferrarini** [ibivu/MA-PRALINE#1]
Hello,

I am trying to run mapraline as showed in Supplementary Docs (https://journals.plos.org/ploscompbiol/article/file?type=supplementary&id=info:doi/10.1371/journal.pcbi.1006547.s002):

`mapraline -a "input_motif.fasta":10 input.fasta output_manual.aln`

However, I keep having this error:

`mapraline: error: argument -p/--pattern is required`

I don't have a prosite motif pattern for the proteins I am using, however I can provide the annotation file.

Did I miss any parameter ?
Thank you very much,
Mariana.

**Comment by mauritsd** [comment]
Hi Mariana,

You have found a bug. :-) I've fixed it in the latest version, which you can install with downloading the source code and running in its directory: `$ python setup.py install`

Could you let me know if that fixes it?

**Comment by mariferrarini** [comment]
For some reason I was not able to make the source code work, however, I reinstalled with pip and tweaked the code directly in the lines 398/399 of cmd.py to correct it. Now it works like a charm!

Not on the same topic, but I also wanted to ask if you have the "alpha" parameter explained somewhere ?

Thank you!

**Comment by mauritsd** [comment]
The article explains the alpha-parameter (or the parameter you give after the ':' for the -p and -a flags) in the methods section and discusses its relevance in the discussion section. 

In short, it's the score bonus that's given when the program tries to match two positions containing an instance of the same motif (either provided through -p or -a). If it's 0 then the method essentially becomes a 'normal' MSA program that doesn't treat motifs any differently. The higher it's set the more MA-PRALINE will try to align motifs over optimising the normal amino acid substitution matrix score (often BLOSUM62). If you make it very high (say, 100000), then matching motifs of that family/annotation file effectively becomes a hard constraint; this can be useful when you want MA-PRALINE to align things you know should be aligned.

**Comment by mariferrarini** [comment]
Got it, thank you very much!
